/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package expensetrackerv3;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.util.Currency;
import java.util.List;
import java.util.regex.Pattern;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author xezt
 */
public class MainFrame extends javax.swing.JFrame {

    public DataLoader dl = new DataLoader();
    public String d;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }
    
    public boolean dataValidator(String data, String typeOfInput){
    
        Pattern pattern = Pattern.compile("-?\\d+(\\.\\d+)?");
        
        boolean type = false;
        double number;
        
        if(typeOfInput.equals("double")){
            if(pattern.matcher(data).matches()){
            type = true;
        }else{
            type = false;
        }   
        }
           
       
        
        return type;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        sidePane = new javax.swing.JPanel();
        setBudgetButton = new javax.swing.JButton();
        viewBudgetButton = new javax.swing.JButton();
        addExpenseButton = new javax.swing.JButton();
        viewExpenseButton = new javax.swing.JButton();
        cardLayoutPane = new javax.swing.JPanel();
        setBudgetPane = new javax.swing.JPanel();
        foodLabel = new javax.swing.JLabel();
        foodTF = new javax.swing.JTextField();
        transportLabel = new javax.swing.JLabel();
        transportTF = new javax.swing.JTextField();
        billsLabel = new javax.swing.JLabel();
        billsTF = new javax.swing.JTextField();
        otherLabel = new javax.swing.JLabel();
        otherTF = new javax.swing.JTextField();
        savingsLabel = new javax.swing.JLabel();
        savingsTF = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        viewBudgetPane = new javax.swing.JPanel();
        foodLabel1 = new javax.swing.JLabel();
        foodLabel2 = new javax.swing.JLabel();
        transportLabel1 = new javax.swing.JLabel();
        transportLabel2 = new javax.swing.JLabel();
        billsLabel1 = new javax.swing.JLabel();
        billsLabel2 = new javax.swing.JLabel();
        otherLabel1 = new javax.swing.JLabel();
        otherLabel2 = new javax.swing.JLabel();
        savingsLabel1 = new javax.swing.JLabel();
        savingsLabel2 = new javax.swing.JLabel();
        addExpensePane = new javax.swing.JPanel();
        expenseLabel = new javax.swing.JLabel();
        expenseETF = new javax.swing.JTextField();
        priceLabel = new javax.swing.JLabel();
        priceETF = new javax.swing.JTextField();
        categoryLabel = new javax.swing.JLabel();
        categoryCB = new javax.swing.JComboBox<>();
        dateLabel = new javax.swing.JLabel();
        dateETF = new javax.swing.JTextField();
        submitExpenseButton = new javax.swing.JButton();
        viewExpensePane = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Expense Tracker");
        setBackground(new java.awt.Color(143, 143, 143));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        sidePane.setBackground(new java.awt.Color(41, 72, 234));

        setBudgetButton.setBackground(new java.awt.Color(61, 90, 241));
        setBudgetButton.setFont(setBudgetButton.getFont().deriveFont(setBudgetButton.getFont().getStyle() | java.awt.Font.BOLD));
        setBudgetButton.setForeground(new java.awt.Color(200, 252, 234));
        setBudgetButton.setText("Set Budget");
        setBudgetButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        setBudgetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setBudgetButtonActionPerformed(evt);
            }
        });

        viewBudgetButton.setText("View Budget");
        viewBudgetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBudgetButtonActionPerformed(evt);
            }
        });

        addExpenseButton.setText("Add Expense");
        addExpenseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addExpenseButtonActionPerformed(evt);
            }
        });

        viewExpenseButton.setText("View Expenses");
        viewExpenseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewExpenseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidePaneLayout = new javax.swing.GroupLayout(sidePane);
        sidePane.setLayout(sidePaneLayout);
        sidePaneLayout.setHorizontalGroup(
            sidePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewBudgetButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addExpenseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewExpenseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(setBudgetButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidePaneLayout.setVerticalGroup(
            sidePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePaneLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(setBudgetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewBudgetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addExpenseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewExpenseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1285, Short.MAX_VALUE))
        );

        getContentPane().add(sidePane);

        cardLayoutPane.setBackground(new java.awt.Color(61, 90, 241));
        cardLayoutPane.setLayout(new java.awt.CardLayout());

        setBudgetPane.setBackground(new java.awt.Color(61, 90, 241));
        setBudgetPane.setToolTipText("");
        setBudgetPane.setOpaque(false);
        java.awt.GridBagLayout setBudgetPaneLayout = new java.awt.GridBagLayout();
        setBudgetPaneLayout.columnWidths = new int[] {50, 100, 50};
        setBudgetPane.setLayout(setBudgetPaneLayout);

        foodLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        foodLabel.setForeground(new java.awt.Color(200, 252, 234));
        foodLabel.setText("Food: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        setBudgetPane.add(foodLabel, gridBagConstraints);

        foodTF.setBackground(new java.awt.Color(61, 90, 241));
        foodTF.setForeground(new java.awt.Color(200, 252, 234));
        foodTF.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(200, 252, 234)));
        foodTF.setCaretColor(new java.awt.Color(41, 72, 234));
        foodTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodTFActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 8, 0);
        setBudgetPane.add(foodTF, gridBagConstraints);

        transportLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        transportLabel.setForeground(new java.awt.Color(200, 252, 234));
        transportLabel.setText("Transport:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        setBudgetPane.add(transportLabel, gridBagConstraints);

        transportTF.setBackground(new java.awt.Color(61, 90, 241));
        transportTF.setForeground(new java.awt.Color(200, 252, 234));
        transportTF.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(200, 252, 234)));
        transportTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transportTFActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(9, 0, 9, 0);
        setBudgetPane.add(transportTF, gridBagConstraints);

        billsLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        billsLabel.setForeground(new java.awt.Color(200, 252, 234));
        billsLabel.setText("Bills:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        setBudgetPane.add(billsLabel, gridBagConstraints);

        billsTF.setBackground(new java.awt.Color(61, 90, 241));
        billsTF.setForeground(new java.awt.Color(200, 252, 234));
        billsTF.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(200, 252, 234)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 8, 0);
        setBudgetPane.add(billsTF, gridBagConstraints);

        otherLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        otherLabel.setForeground(new java.awt.Color(200, 252, 234));
        otherLabel.setText("Other:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        setBudgetPane.add(otherLabel, gridBagConstraints);

        otherTF.setBackground(new java.awt.Color(61, 90, 241));
        otherTF.setForeground(new java.awt.Color(200, 252, 234));
        otherTF.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(200, 252, 234)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 8, 0);
        setBudgetPane.add(otherTF, gridBagConstraints);

        savingsLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        savingsLabel.setForeground(new java.awt.Color(200, 252, 234));
        savingsLabel.setText("Savings:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        setBudgetPane.add(savingsLabel, gridBagConstraints);

        savingsTF.setBackground(new java.awt.Color(61, 90, 241));
        savingsTF.setForeground(new java.awt.Color(200, 252, 234));
        savingsTF.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(200, 252, 234)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 8, 0);
        setBudgetPane.add(savingsTF, gridBagConstraints);

        submitButton.setBackground(new java.awt.Color(41, 72, 234));
        submitButton.setForeground(new java.awt.Color(200, 252, 234));
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        setBudgetPane.add(submitButton, gridBagConstraints);

        cardLayoutPane.add(setBudgetPane, "card2");

        viewBudgetPane.setBackground(new java.awt.Color(61, 90, 241));

        foodLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        foodLabel1.setText("Food: ");

        foodLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        transportLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        transportLabel1.setText("Transport:");

        transportLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        billsLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        billsLabel1.setText("Bills:");

        billsLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        otherLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        otherLabel1.setText("Other:");

        otherLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        savingsLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        savingsLabel1.setText("Savings:");

        savingsLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout viewBudgetPaneLayout = new javax.swing.GroupLayout(viewBudgetPane);
        viewBudgetPane.setLayout(viewBudgetPaneLayout);
        viewBudgetPaneLayout.setHorizontalGroup(
            viewBudgetPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewBudgetPaneLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addGroup(viewBudgetPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewBudgetPaneLayout.createSequentialGroup()
                        .addComponent(savingsLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(savingsLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(viewBudgetPaneLayout.createSequentialGroup()
                        .addGroup(viewBudgetPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(foodLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(transportLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(billsLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(otherLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(viewBudgetPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(foodLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(transportLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(billsLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(otherLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(1111, Short.MAX_VALUE))
        );
        viewBudgetPaneLayout.setVerticalGroup(
            viewBudgetPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewBudgetPaneLayout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addGroup(viewBudgetPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(viewBudgetPaneLayout.createSequentialGroup()
                        .addComponent(foodLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(transportLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(billsLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(otherLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(viewBudgetPaneLayout.createSequentialGroup()
                        .addComponent(foodLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(transportLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(billsLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(otherLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(viewBudgetPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(savingsLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(savingsLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(1255, Short.MAX_VALUE))
        );

        cardLayoutPane.add(viewBudgetPane, "card3");

        addExpensePane.setBackground(new java.awt.Color(61, 90, 241));

        expenseLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        expenseLabel.setText("Expense:");

        expenseETF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expenseETFActionPerformed(evt);
            }
        });

        priceLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        priceLabel.setText("Price:");

        categoryLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        categoryLabel.setText("Category:");

        categoryCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Food", "Transport", "Bills", "Other" }));

        dateLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dateLabel.setText("Date:");

        submitExpenseButton.setText("Submit");
        submitExpenseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitExpenseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addExpensePaneLayout = new javax.swing.GroupLayout(addExpensePane);
        addExpensePane.setLayout(addExpensePaneLayout);
        addExpensePaneLayout.setHorizontalGroup(
            addExpensePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addExpensePaneLayout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addGroup(addExpensePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(submitExpenseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(addExpensePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(addExpensePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(priceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(expenseLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(addExpensePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(dateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(categoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(addExpensePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(expenseETF)
                    .addComponent(priceETF)
                    .addComponent(dateETF)
                    .addComponent(categoryCB, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(1065, Short.MAX_VALUE))
        );
        addExpensePaneLayout.setVerticalGroup(
            addExpensePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addExpensePaneLayout.createSequentialGroup()
                .addContainerGap(1285, Short.MAX_VALUE)
                .addGroup(addExpensePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expenseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expenseETF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addExpensePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceETF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addExpensePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoryCB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addExpensePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateETF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(submitExpenseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(169, 169, 169))
        );

        cardLayoutPane.add(addExpensePane, "card4");

        viewExpensePane.setBackground(new java.awt.Color(61, 90, 241));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTable2);

        javax.swing.GroupLayout viewExpensePaneLayout = new javax.swing.GroupLayout(viewExpensePane);
        viewExpensePane.setLayout(viewExpensePaneLayout);
        viewExpensePaneLayout.setHorizontalGroup(
            viewExpensePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewExpensePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1467, Short.MAX_VALUE)
                .addContainerGap())
        );
        viewExpensePaneLayout.setVerticalGroup(
            viewExpensePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewExpensePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1626, Short.MAX_VALUE)
                .addContainerGap())
        );

        cardLayoutPane.add(viewExpensePane, "card6");

        getContentPane().add(cardLayoutPane);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setBudgetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setBudgetButtonActionPerformed
        // TODO add your handling code here:
        cardLayoutPane.removeAll();
        cardLayoutPane.add(setBudgetPane);
        cardLayoutPane.repaint();
        cardLayoutPane.revalidate();
    }//GEN-LAST:event_setBudgetButtonActionPerformed

    private void viewBudgetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBudgetButtonActionPerformed
        cardLayoutPane.removeAll();

        try {
            d = dl.dataLoad("food");
            foodLabel2.setText(d);

            d = dl.dataLoad("transport");
            transportLabel2.setText(d);

            d = dl.dataLoad("bills");
            billsLabel2.setText(d);

            d = dl.dataLoad("other");
            otherLabel2.setText(d);
            
            d = dl.dataLoad("savings");
            savingsLabel2.setText(d);

            viewBudgetPane.revalidate();

        } catch (IOException ex) {
        }
        cardLayoutPane.add(viewBudgetPane);
        cardLayoutPane.repaint();
        cardLayoutPane.revalidate();
    }//GEN-LAST:event_viewBudgetButtonActionPerformed

    private void addExpenseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addExpenseButtonActionPerformed
        // TODO add your handling code here:
        cardLayoutPane.removeAll();
        cardLayoutPane.add(addExpensePane);
        cardLayoutPane.repaint();
        cardLayoutPane.revalidate();
    }//GEN-LAST:event_addExpenseButtonActionPerformed

    private void transportTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transportTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transportTFActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        String toSave = foodTF.getText() + " " + transportTF.getText() + " " + billsTF.getText() + " " + otherTF.getText() + " " + savingsTF.getText();
        
        if(dataValidator(foodTF.getText(), "double") && dataValidator(transportTF.getText(), "double") && dataValidator(billsTF.getText(), "double") && dataValidator(otherTF.getText(), "double") && dataValidator(savingsTF.getText(), "double")){
            FileWriter fw;
            try {
                fw = new FileWriter("budget.txt");
                fw.write(toSave);
                fw.close();
                
                JOptionPane.showMessageDialog(((JButton)evt.getSource()).getParent(), "Budget set");            
            } 
            catch (IOException ex) {
            }
        }else{
            JOptionPane.showMessageDialog(((JButton)evt.getSource()).getParent(), "Data isn't valid");
        }
        

    }//GEN-LAST:event_submitButtonActionPerformed

    private void expenseETFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expenseETFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expenseETFActionPerformed

    private void submitExpenseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitExpenseButtonActionPerformed
        // TODO add your handling code here:
        
        if(dataValidator(priceETF.getText(), "double")){
            String toSave = expenseETF.getText() + " " + priceETF.getText() + " " + categoryCB.getSelectedItem() + " " + dateETF.getText() + "\n";
            String toSaveV2 = String.format("%-20s/%-20s/%-20s/%-20s\n", expenseETF.getText(), priceETF.getText(), categoryCB.getSelectedItem(), dateETF.getText());
            FileWriter fw;
            try {
                fw = new FileWriter("expense_table.txt", true);
                fw.write(toSaveV2);
                fw.close();
            } catch (IOException ex) {
            }

            try {
                File f = new File("budget.txt");
                BufferedReader br = new BufferedReader(new FileReader(f));
                double var;
                String st;
                st = br.readLine();
                String[] splitted = st.split(" ");

                if(categoryCB.getSelectedItem().equals("Food")){
                    var = Double.parseDouble(splitted[0]) - Double.parseDouble(priceETF.getText());
                    toSave = Double.toString(var) + " " + splitted[1] + " " + splitted[2] + " " + splitted[3];
                }else if(categoryCB.getSelectedItem().equals("Transport")){
                    var = Double.parseDouble(splitted[1]) - Double.parseDouble(priceETF.getText());
                    toSave = splitted[0] + " " + Double.toString(var) + " " + splitted[2] + " " + splitted[3];
                }else if(categoryCB.getSelectedItem().equals("Bills")){
                    var = Double.parseDouble(splitted[2]) - Double.parseDouble(priceETF.getText());
                    toSave = splitted[0] + " " + splitted[1] + " " + Double.toString(var) + " " + splitted[3];
                }else if(categoryCB.getSelectedItem().equals("Other")){
                    var = Double.parseDouble(splitted[3]) - Double.parseDouble(priceETF.getText());
                    toSave = splitted[0] + " " + splitted[1] + " " + splitted[2] + " " + Double.toString(var);
                }

                fw = new FileWriter("budget.txt");
                fw.write(toSave);
                fw.close();
            } catch (IOException ex) {
            }
            
            JOptionPane.showMessageDialog(((JButton)evt.getSource()).getParent(), "Expense added. Budget Updated correctly.");
        }else{
            JOptionPane.showMessageDialog(((JButton)evt.getSource()).getParent(), "Data isn't valid");

        }
        
        

    }//GEN-LAST:event_submitExpenseButtonActionPerformed

    private void foodTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodTFActionPerformed
        double amount = 0;
        // TODO add your handling code here:
    }//GEN-LAST:event_foodTFActionPerformed

    private void viewExpenseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewExpenseButtonActionPerformed
  
                String filepath = "expense_table.txt";
        File f = new File(filepath);
        
        try {
            BufferedReader br = new BufferedReader(new FileReader(f));
            String firstline = br.readLine().trim();
            String[] columnsName = firstline.split(",");
            DefaultTableModel dtmodel = (DefaultTableModel)jTable2.getModel();
            dtmodel.setRowCount(0);
            dtmodel.setColumnIdentifiers(columnsName);
            
            Object[] tableLines = br.lines().toArray();
            
            for(int i = 0; i < tableLines.length; i++){
                String line = tableLines[i].toString().trim();
                String[] dataRow = line.split("/");
                dtmodel.addRow(dataRow);
            }
            
        } catch (FileNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IOException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        cardLayoutPane.removeAll();
        cardLayoutPane.add(viewExpensePane);
        cardLayoutPane.repaint();
        cardLayoutPane.revalidate();
    }//GEN-LAST:event_viewExpenseButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addExpenseButton;
    private javax.swing.JPanel addExpensePane;
    private javax.swing.JLabel billsLabel;
    private javax.swing.JLabel billsLabel1;
    private javax.swing.JLabel billsLabel2;
    private javax.swing.JTextField billsTF;
    private javax.swing.JPanel cardLayoutPane;
    private javax.swing.JComboBox<String> categoryCB;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JTextField dateETF;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JTextField expenseETF;
    private javax.swing.JLabel expenseLabel;
    private javax.swing.JLabel foodLabel;
    private javax.swing.JLabel foodLabel1;
    private javax.swing.JLabel foodLabel2;
    private javax.swing.JTextField foodTF;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel otherLabel;
    private javax.swing.JLabel otherLabel1;
    private javax.swing.JLabel otherLabel2;
    private javax.swing.JTextField otherTF;
    private javax.swing.JTextField priceETF;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel savingsLabel;
    private javax.swing.JLabel savingsLabel1;
    private javax.swing.JLabel savingsLabel2;
    private javax.swing.JTextField savingsTF;
    private javax.swing.JButton setBudgetButton;
    private javax.swing.JPanel setBudgetPane;
    private javax.swing.JPanel sidePane;
    private javax.swing.JButton submitButton;
    private javax.swing.JButton submitExpenseButton;
    private javax.swing.JLabel transportLabel;
    private javax.swing.JLabel transportLabel1;
    private javax.swing.JLabel transportLabel2;
    private javax.swing.JTextField transportTF;
    private javax.swing.JButton viewBudgetButton;
    private javax.swing.JPanel viewBudgetPane;
    private javax.swing.JButton viewExpenseButton;
    private javax.swing.JPanel viewExpensePane;
    // End of variables declaration//GEN-END:variables
}
